# Intro to numpy
## Getting to know the library.

In [2]:
import numpy as np

In [4]:
#creation of arrays.
print(np.arange(0,10))

print (np.arange(0, 10) ** 3)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   8  27  64 125 216 343 512 729]


In [18]:
#Create from a function
print (np.fromfunction(lambda i, j: (2 * np.pi) / (i+1) , (6, 1)))


[[ 6.28318531]
 [ 3.14159265]
 [ 2.0943951 ]
 [ 1.57079633]
 [ 1.25663706]
 [ 1.04719755]]


In [21]:
#Create Random Data (0-1)
print (np.random.rand(3,3))

[[ 0.14517523  0.76947689  0.38989825]
 [ 0.45316718  0.91716598  0.58663613]
 [ 0.89917611  0.71119735  0.02476086]]


In [26]:
#Sum the array or along an axis.
print(np.sum([[0,1], [0, 5]]))
print(np.sum([[0,1], [0, 5]], axis=1))


6
[1 5]


In [27]:
#calculate the cumulative sum
print (np.cumsum([0,1,2,3,4,5]))

[ 0  1  3  6 10 15]


In [28]:
#Calculate the mean.
print (np.mean([0,1,2,3,4,5]))


2.5


In [32]:
#Calculate the weighted average
print (np.average(range(0,10), weights=range(20,0,-2)))

3.0


In [33]:
print (np.tan((np.pi)/4))

1.0


In [36]:
#statistics functions.
print (np.amin([1,4,5,-5,7]))
print (np.histogram([1,4,4,4,5,10], bins=[0,5,10]))


-5
(array([4, 2]), array([ 0,  5, 10]))


In [39]:
#Set Commands
print (np.union1d ([1,2,3,4,5], [8,7,6,5,1,0]))
print (np.intersect1d ([1,2,3,4,5], [8,7,6,5,1,0]))


[0 1 2 3 4 5 6 7 8]
[1 5]
